---
title: "Weather Drilldown in the Largest 5 New York Cities (2000 - 2010)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
## Top Largest Cities in NY are: Albany, Buffalo, NYC, Rochester and Syracuse
 
nyweather_data = 
  ny_noaa %>%
  filter(str_detect(id, c("USW00014733|USW00014735|USW00014768|USW00014771|USW00094789"))) %>%
  mutate(name = recode(id, USW00014733 = "NYC",
                      USW00014735 = "Buffalo",
                      USW00014768 = "Rochester",
                      USW00014771 = "Syracuse",
                      USW00094789 = "Albany"),
         prcp = as.numeric(prcp), 
         tmin = as.numeric(tmin),
         tmax = as.numeric(tmax),
         prcp = prcp / 10,
         tmin = tmin / 10,
         tmax = tmax / 10) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month_name = month.name[as.numeric(month)],
         year = as.integer(year)) %>% 
  filter((year) > 1999) %>% 
  select(name, id, year, month, month_name, day, tmin, tmax, prcp)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Maximum Temperature Distribution by Month

```{r}
nyweather_data %>% 
  rename(max_temperature = tmax) %>% 
  mutate(month = as.integer(month),
         month_name = forcats::fct_reorder(month_name, month)) %>% 
  plot_ly(y = ~max_temperature, color = ~month_name, type = "box",
          colors = "Set2")

class(nyweather_data$month)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Maximum Monthly Temperature by City Over Time

```{r}
nyweather_data %>%
  group_by(name, year) %>% 
  summarise(mean_annual_max_temperature = mean(tmax)) %>% 
  plot_ly(x = ~year, y = ~mean_annual_max_temperature, type = "scatter", mode = "lines",
          alpha = 0.5, 
          color = ~name)
```

### Cumulative Monthly Rainfall Over Time

```{r}
nyweather_data %>% 
  mutate(year_month = paste(year, month, sep = "-")) %>% 
  group_by(year_month) %>% 
  summarise(total_rainfall = sum(prcp, na.rm = TRUE)) %>% 
  plot_ly(x = ~year_month, y = ~total_rainfall, type = "bar")
```
